version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: typeform-agent
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-America/Sao_Paulo}
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Volumes somente para dados persistentes
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      # Em produção, não monte o código fonte
      # Em desenvolvimento, descomente a linha abaixo
      # - ./src:/app/src
    # Descomente para desenvolvimento
    # command: npm run dev

  # Serviço para desenvolvimento (descomente se necessário)
  # dev:
  #   build:
  #     context: .
  #     target: development
  #   container_name: typeform-agent-dev
  #   ports:
  #     - "3001:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=development
  #     - NODE_OPTIONS=--inspect=0.0.0.0:9229
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev

# Volumes nomeados para persistência de dados
volumes:
  app_data:
  app_logs:

volumes:
  data:
  logs:
